%YAML:1.0
---
ship_pix_size: !!opencv-matrix
   rows: 1
   cols: 2
   dt: i
   data: [ 300 , 1500 ]
shift_width: !!opencv-matrix
    rows: 1
    cols: 1
    dt: i
    data: [ 500 ]
shift_height: !!opencv-matrix
    rows: 1
    cols: 1
    dt: i
    data: [ 500 ]
inn_shift_width: !!opencv-matrix
    rows: 1
    cols: 1
    dt: i
    data: [ 100 ]
inn_shift_height: !!opencv-matrix
    rows: 1
    cols: 1
    dt: i
    data: [ 100 ]
calib_block_SS_size: !!opencv-matrix
    rows: 1
    cols: 2
    dt: i
    data: [ 150 , 1100 ]
calib_block_FA_size: !!opencv-matrix
    rows: 1
    cols: 2
    dt: i
    data: [ 700 , 150 ]


