%YAML:1.0
---
camera_name: right_back
src_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 359., 458., 292., 442., 354., 300., 396., 309. ]
dst_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 100., 100., 250., 100., 250., 1200., 100., 1200. ]
