%YAML:1.0
---
camera_name: right_front
src_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 367., 295., 401., 291., 479., 451., 408., 474. ]
dst_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 100., 500., 250., 500., 250., 1600., 100., 1600. ]
