%YAML:1.0
---
camera_name: right_back
src_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 356., 458., 289., 438., 342., 327., 385., 335. ]
dst_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 100., 100., 250., 100., 250., 1200., 100., 1200. ]
