%YAML:1.0
---
camera_name: front
src_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 360., 322., 406., 318., 478., 432., 392., 474. ]
dst_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 1087., 525., 1662., 512., 1675., 1362., 1300., 1362. ]
