%YAML:1.0
---
camera_name: back
src_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 352., 478., 282., 456., 354., 284., 404., 294. ]
dst_points: !!opencv-matrix
   rows: 4
   cols: 2
   dt: f
   data: [ 1175., 1375., 1487., 1375., 1525., 2437., 1075., 2387. ]
