camera_name: back
dst_points:
- - 51.0
  - 549.0
- - 197.0
  - 549.0
- - 203.0
  - 891.0
- - 50.0
  - 891.0
src_points:
- - 349.0
  - 468.0
- - 285.0
  - 448.0
- - 359.0
  - 294.0
- - 389.0
  - 299.0
